config/routes.rb
Rails.application.routes.draw do
  resources :todos

   root 'todos#index'

end

app/models/todo.rb
class Todo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.fetch(:todo, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>

app/views/todos/_form.html.erb
<%= form_for(@todo) do |f| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% @todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1>Editing Todo</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<p id="notice"><%= notice %></p>
<section class="habitaciones">
  <div class="row">
    <h2>Habitaciones</h2>
  </div>
  <div class="row">
    <div class="medium-4 columns">
      <a href="#">
        <div class="imagen">
          <img src="assets/images/rooms/room-01.jpg">
          <div class="titulo">
            <h3>Habitaci`on 01</h3>
          </div>
        </div>
        <div class="contenido">
          <p> nose que madre, porque yo no se que pedo con esta cosa. solo se que estoy haciendo algo para aprender algo practico css foundatios.</p>
        </div>
      </a>
    </div>
    <div class="medium-4 columns">
      <a href="#">
        <div class="imagen">
          <%=image_tag("/images/rooms/room-03.jpg")%>
          <div class="titulo">
            <h3>Habitaci`on 02</h3>
          </div>
        </div>
        <div class="contenido">
          <p> nose que madre, porque yo no se que pedo con esta cosa. solo se que estoy haciendo algo para aprender algo practico css foundatios.</p>
        </div>
      </a>
    </div>
    <div class="medium-4 columns">
      <a href="#">
        <div class="imagen">
          <img src="assets/images/rooms/room-03.jpg">
          <div class="titulo">
            <h3>Habitaci`on 03</h3>
          </div>
        </div>
        <div class="contenido">
          <p> nose que madre, porque yo no se que pedo con esta cosa. solo se que estoy haciendo algo para aprender algo practico css foundatios.</p>
        </div>
      </a>
    </div>
  </div>
</section>

app/views/todos/new.html.erb
<h1>New Todo</h1>

<%= render 'form' %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>